language: csharp
dist: trusty
dotnet: 1.0.4
mono: latest
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - mono .paket/paket.bootstrapper.exe
  - dotnet restore
  - dotnet build