language: csharp
dist: trusty
dotnet: 1.0.4
mono: latest
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_script: 
  - chmod +x ./restore.sh
script:
  - ./restore.sh
  - dotnet build